### ISSUE TITLE
not compatible here with PW3dev

### ISSUE THREAD

**Issue by tbba** [plauclair/SuperSmartypants#1]
the module crashes at compling on localhost/MAMP.

this fixed it for me:
line 34:  require_once("./smartypants.php");

**Comment by tbba** [comment]
Sorry, the solution is not that easy, My solution makes a problem with the backward compatibility.
I close this for now.

**Comment by plauclair** [comment]
Hi, thanks for the feedback. It sounds like an environment issue, maybe a MAMP configuration issue as I do regular dev on Mac/Win/Linux and have yet to encounter a problem. Let me know if you can pinpoint the issue.

**Comment by tbba** [comment]
Hi, that is interesting. Can you confirm you tested the _PW 3.0.4 alpha_ with the module and MAMP sucessfully?
This could be really helpful information for me to dig further.

**Comment by plauclair** [comment]
I don't use MAMP, I use the system's Apache and this PHP build http://php-osx.liip.ch.

**Comment by plauclair** [comment]
Oh I just realized you are using 3.x alpha. I don't support this version yet (so it may work or not). I typically will only support releases on the 2.x branch. 3.x is really new and things may not work, things are bound to change a lot and I don't want to fix things on a moving target.

**Comment by tbba** [comment]
Ah, ok. In the meantime I reverted PW back to 2.x so everything runs again.
